baseURL = "https://damian.pecke.tt/"
languageCode = "en-us"
title = '''Damian Peckett's Blog'''
theme = "mini"

[permalinks]
  posts = "/posts/:title/"

[social]
  github = "https://github.com/dpeckett/"
  linkedin = "https://www.linkedin.com/in/damian-peckett-ba7536a9/"
  
[params]
  author = "Damian Peckett"
  mainSections = ["blog"]
  
[[params.links]]
  path = "/legal/privacy"
  name = "Privacy Policy"
  
[[params.links]]
  path = "/legal/imprint"
  name = "Imprint"